services:
  oblivion-planner:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '${PORT}:${PORT}'
    environment:
      - NODE_ENV=production
    env_file:
      - .env.local
    restart: always
    profiles:
      - production

  oblivion-planner-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env.local
    restart: unless-stopped
    profiles:
      - development

volumes:
  node_modules:
